import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
    container: {
      paddingTop:80,
      padding:25,
      width:'100%',
      backgroundColor: '#FFFFFF'
    },
  
    Button:{
        marginTop: 25,
        width:'100%',
        borderColor:'#eee',
        backgroundColor:'#00aeef',
        borderBottomWidth:0,
        alignItems: 'center',
    },
    Button2:{
      marginTop: 15,
      width:'100%',
      borderColor:'#eee',
      borderBottomWidth:0,
      alignItems: 'center',
  },
    label:{
        padding: 5,
        paddingTop:0.,
        color:'#333',
        fontSize:18,
        fontWeight:'500',
        width: '100%',
    },
    Appbar: {
      width:'100%',
      backgroundColor: '#00aeef'
    },
    Button_1:{
      width:'35%', 
      borderColor:'#eee',
      backgroundColor:'#00aeef',
      borderBottomWidth:0,
      alignItems: 'center',
      position:'absolute',
      right:0,
      left:'3%',
      Button:0,
      top:'85%',
  },
  Button_2:{
    width:'35%',
    borderColor:'#eee',
    borderBottomWidth:0,
    alignItems: 'center',
    position:'absolute',
    right:0,
    left:'60%',
    Button:0,
    top:'85%',
  },
  ContrainerModel:{
    flex:1,
    display:'flex',
    backgroundColor:"#ECE8E7",
    borderWidth:1,
    borderColor:"black",
    width:'90%',
    maxHeight:'65%',
    position:'relative',
    left:'5%',
    top:'20%',
    borderRadius:10,
  },
  input1 :{
    flex:1,
    justifyContent: 'center',
    position:'absolute',
    bottom:'60%',
    left:10,
    right:10,
    backgroundColor:'#ffff'
  }, 
  input2 :{
    flex:1,
    justifyContent: 'center',
    position:'absolute',
    bottom:'30%',
    left:10,
    right:10,
    backgroundColor:'#ffff'
  }, 
  Button1Model:{
    width:'35%', 
    borderColor:'#eee',
    backgroundColor:'#C44425',
    borderBottomWidth:0,
    alignItems: 'center',
    position:'absolute',
    right:0,
    left:'3%',
    Button:0,
    top:'72%',
  },
  Button2Model:{
    width:'35%',
    backgroundColor:'#00aeef',
    borderBottomWidth:0,
    alignItems: 'center',
    position:'absolute',
    right:0,
    left:'60%',
    Button:0,
    top:'72%',
  },
});

